namespace: my_own_namespace
name: yandex_cloud_elk
version: 1.0.0
readme: README.md
authors:
  - Student <m.a.pertsev@yandex.ru>
description: Custom Ansible collection for file creation
license:
  - GPL-3.0-or-later
tags:
  - file
  - creation
  - custom
repository: https://github.com/Furious992/my_own_collection
documentation: https://github.com/Furious992/my_own_collection
homepage: https://github.com/Furious992/my_own_collection
issues: https://github.com/Furious992/my_own_collection/issues
build_ignore: []
dependencies: {}
